### ISSUE TITLE
Flask 2.3.1 leads to pyload crash on build from develop branch

### ISSUE THREAD

**Issue by aptalca** [pyload/pyload#4286]
### Description

pyLoad-ng develop branch build with Flask 2.3.1 (just released) leads to crash on start

### Debug log

```
[2023-04-26 06:06:26]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2023-04-26 06:06:26]  DEBUG               pyload  Indexing plugins...
[2023-04-26 06:06:26]  INFO                pyload  Activated addons: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher
[2023-04-26 06:06:26]  INFO                pyload  Deactivate addons: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XFileSharing, XMPP
AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
Traceback (most recent call last):
  File "/usr/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pyload/__main__.py", line 292, in main
    run(core_args, args.daemon, args.pidfile)
  File "/usr/lib/python3.10/site-packages/pyload/__main__.py", line 235, in run
    pyload_core = Core(*core_args)
  File "/usr/lib/python3.10/site-packages/pyload/core/__init__.py", line 105, in __init__
    self._init_webserver()
  File "/usr/lib/python3.10/site-packages/pyload/core/__init__.py", line 168, in _init_webserver
    from pyload.webui.webserver_thread import WebServerThread
  File "/usr/lib/python3.10/site-packages/pyload/webui/webserver_thread.py", line 9, in <module>
    from .app import App
  File "/usr/lib/python3.10/site-packages/pyload/webui/app/__init__.py", line 17, in <module>
    from .blueprints import BLUEPRINTS
  File "/usr/lib/python3.10/site-packages/pyload/webui/app/blueprints/__init__.py", line 11, in <module>
    from .app_blueprint import bp as app_bp
  File "/usr/lib/python3.10/site-packages/pyload/webui/app/blueprints/app_blueprint.py", line 17, in <module>
    from ..helpers import (
  File "/usr/lib/python3.10/site-packages/pyload/webui/app/helpers.py", line 11, in <module>
    class JSONEncoder(flask.json.JSONEncoder):
AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```

### Additional references

This is running in the Linuxserver.io docker image: https://github.com/linuxserver/docker-pyload-ng/tree/develop

Not sure if this is a pyload issue or a flask issue. I wanted to bring it up here first and if it is upstream, please let me know and I'll move it over there.

### Screenshots

N/A

Thanks

PS. Here is the build report on the latest commit to develop branch: https://ci-tests.linuxserver.io/linuxserver/pyload-ng/develop-2c5d66b4-ls228/index.html

**Comment by GammaC0de** [comment]
pyLoad is a client-server software with the goal to be able to install and use it on headless machines such as NASs.
To do so, we try to support as much as python versions as possible.
Only Flask version 2.0 supports python 3.6 so this is what we use (see https://github.com/pyload/pyload/blob/main/setup.cfg#L69).

Flask 2.3 that linuxserver uses is not compatible with 2.0.

**Comment by aptalca** [comment]
Thanks @GammaC0de, but your dependency is defined as `Flask~=2.0`, which leads pip to install `2.3.1`
To be clear, we're not making the decision to install Flask 2.3.1, it gets installed as a dep of pyload-ng by pip
All we do in that dev image is `pip3 install "git+https://github.com/pyload/pyload.git@${PYLOAD_COMMIT}"`

```
# pip3 install Flask~=2.0
Collecting Flask~=2.0
  Downloading Flask-2.3.1-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.0/97.0 kB 1.3 MB/s eta 0:00:00
Collecting Werkzeug>=2.3.0 (from Flask~=2.0)
  Downloading Werkzeug-2.3.0-py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.7/233.7 kB 4.8 MB/s eta 0:00:00
Collecting Jinja2>=3.1.2 (from Flask~=2.0)
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 3.3 MB/s eta 0:00:00
Collecting itsdangerous>=2.1.2 (from Flask~=2.0)
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.1.3 (from Flask~=2.0)
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 8.3 MB/s eta 0:00:00
Collecting blinker>=1.6.2 (from Flask~=2.0)
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1.2->Flask~=2.0)
  Downloading MarkupSafe-2.1.2-cp310-cp310-musllinux_1_1_x86_64.whl (29 kB)
Installing collected packages: MarkupSafe, itsdangerous, click, blinker, Werkzeug, Jinja2, Flask
Successfully installed Flask-2.3.1 Jinja2-3.1.2 MarkupSafe-2.1.2 Werkzeug-2.3.0 blinker-1.6.2 click-8.1.3 itsdangerous-2.1.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by GammaC0de** [comment]
Should work now, please confirm.

**Comment by aptalca** [comment]
Yes, it does. Flask is version 2.0.3. Thanks so much!

https://ci-tests.linuxserver.io/linuxserver/pyload-ng/develop-1e0e419f-ls228/index.html
