### ISSUE TITLE
RestartFailed ERROR

### ISSUE THREAD

**Issue by de666** [pyload/pyload#138]
After updating to 1.6 version of RestartFailed plugin, this error is shown every minute:

27.05.2013 11:30:38 ERROR Error executing hooks: 'NoneType' object has no attribute '**getitem**'
Traceback (most recent call last):
File "/opt/pyload/module/plugins/Hook.py", line 100, in _periodical
if self.isActivated(): self.periodical()
File "/var/lib/pyload/userplugins/hooks/RestartFailed.py", line 58, in periodical
if self.info["timerflag"]:
TypeError: 'NoneType' object has no attribute '__getitem__'
