### ISSUE TITLE
UlozTo premium account not working on 0.4.9 stable ...again

### ISSUE THREAD

**Issue by realsuso** [pyload/pyload#2931]
Hi,
I have this warning message in the log file and the account status show non-premium again.

295 | 14.08.2017 14:50:26 | INFO | Activating Accounts...
296 | 14.08.2017 14:50:27 | INFO | ACCOUNT UlozTo: Adding user `jin*******`...
297 | 14.08.2017 14:50:27 | INFO | ACCOUNT UlozTo: Login user `jin*******`...
298 | 14.08.2017 14:50:31 | INFO | ACCOUNT UlozTo: Grabbing account info for user `jin*******`...
299 | 14.08.2017 14:50:32 | WARNING | ACCOUNT UlozTo: Error loading info for user `jin*******` \| __init__() got an unexpected keyword argument 'get'
300 | 14.08.2017 14:50:32 | INFO | Activating Plugins...
301 | 14.08.2017 14:50:32 | INFO | ADDON UpdateManager

**Comment by realsuso** [comment]
works again...many many thanx!
