### ISSUE TITLE
OneFichierCom TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#1679]
I wanted to perform some feedback around the filename under the plugin OneFichierCom (the_name_of_file filename=UTF8-the_name_of_file),
but OneFichierCom is not working any more.....

here is the debug file :
```DEBUG
pyLoad 0.4.9 Debug Report of OneFichierCom 0.86

TRACEBACK:
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/pyload/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 281, in process
    self.preload()
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 255, in preload
    decode=self.TEXT_ENCODING)
  File "/opt/pyload/userplugins/internal/Plugin.py", line 338, in load
    set_cookies(req.cj, cookies)
  File "/opt/pyload/userplugins/internal/Plugin.py", line 90, in set_cookies
    for cookie in cookies:
TypeError: 'bool' object is not iterable
```

``` 
FRAMESTACK:

Frame preprocessing in /opt/pyload/userplugins/internal/Hoster.py at line 184
                        self = <userplugins.hoster.OneFichierCom.OneFichierCom object at 0x7f69434bf650>
                      thread = <DownloadThread(Thread-2, started daemon 140090619516672)>

Frame process in /opt/pyload/userplugins/internal/SimpleHoster.py at line 306
                      pyfile = PyFile 422: ######@OneFichierCom
                        self = <userplugins.hoster.OneFichierCom.OneFichierCom object at 0x7f69434bf650>

Frame preload in /opt/pyload/userplugins/internal/SimpleHoster.py at line 255
                        self = <userplugins.hoster.OneFichierCom.OneFichierCom object at 0x7f69434bf650>

Frame load in /opt/pyload/userplugins/internal/Plugin.py at line 338
                     cookies = True
                         val = False
                         get = {}
                         url = u'https://######.1fichier.com'
                        self = <userplugins.hoster.OneFichierCom.OneFichierCom object at 0x7f69434bf650>
                         req = <module.network.Browser.Browser object at 0x7f69434ba3f8>
                      decode = True
                   multipart = False
                         key = 'just_header'
                        post = {}
                         ref = False
                 just_header = False

Frame set_cookies in /opt/pyload/userplugins/internal/Plugin.py at line 90
                          cj = <module.network.CookieJar.CookieJar instance at 0x7f69435633b0>
                     cookies = True
```

``` 
PLUGIN OBJECT DUMP:

                  CHECK_FILE = True
               CHECK_TRAFFIC = False
                     COOKIES = [('1fichier.com', 'LG', 'en')]
                 DIRECT_LINK = None
                 DISPOSITION = True
                 FILE_ERRORS = [('Html error',
  '\\A(?:\\s*<.+>)?((?:[\\w\\s]*(?:[Ee]rror|ERROR)\\s*\\:?)?\\s*\\d{3})(?:\\Z|\\s+)'),
 ('Request error', '([Aa]n error occured while processing your request)'),
 ('Html file', '\\A\\s*<!DOCTYPE html')]
                LEECH_HOSTER = False
                LINK_PATTERN = None
               LOGIN_ACCOUNT = False
               LOGIN_PREMIUM = False
                NAME_PATTERN = '>FileName :</td>\\s*<td.*>(?P<N>.+?)<'
           NAME_REPLACEMENTS = [('&#?\\w+;', <function fixup at 0x7f69682cade8>)]
             OFFLINE_PATTERN = 'File not found !\\s*<'
                SIZE_PATTERN = '>Size :</td>\\s*<td.*>(?P<S>[\\d.,]+) (?P<U>[\\w^_]+)'
           SIZE_REPLACEMENTS = []
               TEXT_ENCODING = True
            URL_REPLACEMENTS = []
                WAIT_PATTERN = '>You must wait \\d+ minutes'
                     account = False
                     captcha = <userplugins.internal.Captcha.Captcha object at 0x7f69434bff10>
                 chunk_limit = 1
                   direct_dl = False
                        html = ''
                        info = {'folder': u'######',
 'name': u'######',
 'pattern': {'HOST': u'1fichier.com', 'ID1': u'######', 'ID2': None},
 'size': 0,
 'status': 3,
 'url': u'https://######.1fichier.com'}
                          js = <module.common.JsEngine.JsEngine instance at 0x7f69619b7830>
                  last_check = None
               last_download = ''
                    leech_dl = False
                     limitDL = 0
                        link = ''
                     multiDL = False
                     premium = False
                      pyfile = PyFile 422: ######@OneFichierCom
                      pyload = <__main__.Core object at 0x7f696444d1d0>
                         req = <module.network.Browser.Browser object at 0x7f69434ba3f8>
             resume_download = True
                     retries = {}
                  retry_free = False
                      thread = <DownloadThread(Thread-2, started daemon 140090619516672)>
                        user = None
                  wait_until = 0
                     waiting = False
               wantReconnect = False
```

``` 
PYFILE OBJECT DUMP:

                       _size = 0
                       abort = False
                      active = False
                       error = "'bool' object is not iterable"
                          id = 422
                        lock = <_RLock owner=None count=0>
                           m = <module.database.FileDatabase.FileHandler instance at 0x7f69643c8830>
                 maxprogress = 100
                        name = u'######'
                       order = 5
                   packageid = 7
                      plugin = <userplugins.hoster.OneFichierCom.OneFichierCom object at 0x7f69434bf650>
                 pluginclass = <class 'userplugins.hoster.OneFichierCom.OneFichierCom'>
                pluginmodule = <module 'userplugins.hoster.OneFichierCom' from '/opt/pyload/userplugins/hoster/OneFichierCom.pyc'>
                  pluginname = u'OneFichierCom'
                    progress = 0
                 reconnected = False
                        size = 0
                      status = 8
                  statusname = None
                         url = u'https://######.1fichier.com/'
                   waitUntil = 0
```

``` 
CONFIG:

{'desc': 'OneFichierCom',
 'outline': '1fichier.com hoster plugin',
 'use_premium': {'desc': 'Use premium account if available',
                 'type': 'bool',
                 'value': True}}
```

**Comment by zephura** [comment]
I'v tried something...
in the file "userplugins/internal/Plugin.py" on line 338
```
        #@TODO: Move to network in 0.4.10
        if isinstance(self.COOKIES, list):
-             set_cookies(req.cj, cookies)
+             set_cookies(req.cj, self.COOKIES)

        res = req.load(url, get, post, ref, bool(cookies), just_header, multipart, decode is True)  #@TODO: Fix network multipart in 0.4.10
```

It seems to work.
Anyone could try to verify ?

**Comment by drmedramme** [comment]
Hi. I tried to verify - unfortunately it did not help in my case. (UploadedTo, ShareonlineBiz)

**Comment by zephura** [comment]
For shareonlinebiz I cannot help, I do not have JS engine (spidermonkey is not working)
I'll try a uploaded.to link to see

**Comment by snickers2k** [comment]
same here for premiumize

HOOK PremiumizeMe: 'bool' object has no attribute 'select' | Waiting 1 minute and retry

**Comment by drmedramme** [comment]
Check this out:
https://github.com/pyload/pyload/pull/1685

It worked for me.

**Comment by bistory** [comment]
Replacing the files manually as suggested by @drmedramme doesn't work...
