### ISSUE TITLE
UlozTo premium account not working on 0.4.9 stable

### ISSUE THREAD

**Issue by realsuso** [pyload/pyload#2927]
Hi,
I have problem to setup an UlozTo premium account on the actual stable version of pyload. 
After adding the account in the webgui some warning apiers in the log: 

11.08.2017 21:51:34 INFO      ACCOUNT UlozTo: Adding user `jin*******`...
11.08.2017 21:51:34 INFO      ACCOUNT UlozTo: Login user `jin*******`...
11.08.2017 21:51:38 INFO      ACCOUNT UlozTo: Grabbing account info for user `jin*******`...
11.08.2017 21:51:39 WARNING   ACCOUNT UlozTo: Error loading info for user `jin*******` | 'NoneType' object has no attribute 'group'

The account is then recogized as non-premium, this means downloading from uloz.to works only with captcha.

I found this same issue on a RaspberryPi3+Raspbian.Jessie.Lite and on my ZyXel NAS wih thies spesc:
System
Python: 	2.6.2 (r262:33865M, Dec 15 2011, 17:59:38) [GCC 4.3.2]
OS: 	posix linux2 Linux nsa310 2.6.31.8 #2 Fri Mar 11 17:35:20 CST 2016 armv5tel
pyLoad version: 	0.4.9

THX for help.

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by realsuso** [comment]
account info sent

**Comment by realsuso** [comment]
tested...works great...THX

**Comment by GammaC0de** [comment]
👍
