### ISSUE TITLE
Unable to activate SkipRev

### ISSUE THREAD

**Issue by mobo95** [pyload/pyload#1714]
<pre><code>
05.08.2015 12:10:23 DEBUG Plugin loaded: SkipRev
05.08.2015 12:10:23 WARNING   Error calling event handler pluginConfigChanged: <bound method HookManager.manageHooks of <module.HookManager.HookManager instance at 0x8277a6c>>, ('SkipRev', 'activated', True), 'Core' object has no attribute 'pyfile'
</code></pre>

**Comment by GammaC0de** [comment]
```
Traceback (most recent call last):
  File "/usr/share/pyload/module/HookManager.py", line 309, in dispatchEvent
    f(*args)
  File "/usr/share/pyload/module/HookManager.py", line 151, in manageHooks
    self.activateHook(plugin)
  File "/usr/share/pyload/module/HookManager.py", line 168, in activateHook
    plugin = pluginClass(self.core, self)
  File "/home/user/.pyload-0.4.9/userplugins/internal/Addon.py", line 40, in __init__
    self._init(core)
  File "/home/user/.pyload-0.4.9/userplugins/hooks/SkipRev.py", line 29, in _init
    self.pyfile.plugin._init()
AttributeError: 'Core' object has no attribute 'pyfile'
```
@vuolter:
What is the purpose the call to `_init` in `Addon.py`? (it was introduced in https://github.com/pyload/pyload/commit/84f2193d76f7c6f47c834dc8902d8ead8e45a11a , [line 30](https://github.com/pyload/pyload/blob/84f2193d76f7c6f47c834dc8902d8ead8e45a11a/module/plugins/internal/Account.py#L30))
