### ISSUE TITLE
http://www.easybytez.com/ error

### ISSUE THREAD

**Issue by alby1979** [pyload/pyload#3527]
hi

DEBUG | ACCOUNT EasybytezCom: LOAD URL http://www.easybytez.com/login.html \| redirect=True \| decode=True \| cookies=True \| get={} \| req=None \| just_header=False \| post={} \| ref=True \| multipart=False
-- | --

ERROR | ACCOUNT EasybytezCom: Could not login user `ka1*******` \| sub() got an unexpected keyword argument 'flags'
-- | --

thanks

**Comment by GammaC0de** [comment]
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment]
Works fine for me,
Please refresh your pyLoad installation using the instruction in #3283 and then retry.

**Comment by alby1979** [comment]
I tried with the guide. I install 0.4.20 and it doesn't work.

I see I find the old stable.zip with 0.4.9 and with that I remember it worked

**Comment by alby1979** [comment]
I just tried again. With stable.zip 0.4.9 easybyte works.
does not work with 0.4.20

**Comment by GammaC0de** [comment]
Please refresh your pyLoad installation (again) using the instruction in #3283 and then retry,
Your issue should be resolved.

**Comment by alby1979** [comment]
thank you very much
now work very well
