### ISSUE TITLE
Can't download with DLC or URL

### ISSUE THREAD

**Issue by Sporrdig** [pyload/pyload#1675]
DLC:
Added package test containing 1 links
DEBUG     Redirected import module.plugins.container.DLC -> userplugins.container.DLC
 DEBUG     Redirected import module.plugins.internal.Crypter -> userplugins.internal.Crypter
 DEBUG     Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
INFO      Decrypting starts: Downloads/tmp_n2wdn156jeese93.dlc
DEBUG     HOOK UserAgentSwitcher: Use custom user-agent string: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
 DEBUG     CONTAINER DLC[1]: PROCESS URL Downloads/tmp_n2wdn156jeese93.dlc | PLUGIN VERSION 0.26
 DEBUG     CONTAINER DLC[1]: LOAD URL http://service.jdownloader.org/dlcrypt/service.php?srcType=dlc&destType=pylo&data=SXowQWtkdFVITHVYbGk5UmR3bVlXb2tOM05ON2ptcXVvWTNMUWFnUGFlRk11L3JTYjBtU2NudXpPWFQ4d2Y4eA== | decode=True | cookies=True | get={} | req=None | _[1]=['decode=True', 'cookies=True', 'get={}', 'req=None'] | multipart=False | post={} | ref=True | just_header=False
 ERROR     Decrypting failed: tmp_n2wdn156jeese93.dlc | 'DLC' object has no attribute 'COOKIES'
 DEBUG     Error creating zip file: 'ascii' codec can't decode byte 0xaf in position 16: ordinal not in range(128)
INFO      Debug Report written to debug_DLC_03-08-2015_05-10-02.txt

Debug log:
pyLoad 0.4.9 Debug Report of DLC 0.26 

TRACEBACK:
 Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/PluginThread.py", line 363, in run
    self.active.plugin.preprocessing(self)
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self.process(self.pyfile)
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/internal/Container.py", line 34, in process
    self.decrypt(pyfile)
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/container/DLC.py", line 45, in decrypt
    dlc_content = self.load(self.API_URL % dlc_key)
  File "/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/Plugin.py", line 337, in load
    if isinstance(self.COOKIES, list):
AttributeError: 'DLC' object has no attribute 'COOKIES'
 

FRAMESTACK:

Frame preprocessing in /share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/Hoster.py at line 184
	                self = <userplugins.container.DLC.DLC object at 0x870594c>
	              thread = <DecrypterThread(Thread-12, started daemon)>

Frame process in /share/CACHEDEV1_DATA/.qpkg/pyload/module/plugins/internal/Container.py at line 34
	              pyfile = PyFile 1: tmp_n2wdn156jeese93.dlc@DLC
	                self = <userplugins.container.DLC.DLC object at 0x870594c>

Frame decrypt in /share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/container/DLC.py at line 45
	                 dlc = <closed file u'Downloads/tmp_n2wdn156jeese93.dlc', mode 'r' at 0x8706458>
	              pyfile = PyFile 1: tmp_n2wdn156jeese93.dlc@DLC
	             dlc_key = 'SXowQWtkdFVITHVYbGk5UmR3bVlXb2tOM05ON2ptcXVvWTNMUWFnUGFlRk11L3JTYjBtU2NudXpPWFQ4d2Y4eA=='
	         fs_filename = u'Downloads/tmp_n2wdn156jeese93.dlc'
	                self = <userplugins.container.DLC.DLC object at 0x870594c>
	            dlc_data = '\x1b\xa9(\x1a\x8b\xd6\xde\x99\xe6\xbe\xb0N\xbb\xf1\x99\xfc\x9b)\x94>\x8a\x92\xed8\xae<T\xae\xa3\xd1\xf5JUWix\xe6\x02~e\x14\x01\xc9 \xa4\tw!\xca}\xa1\xc9?\xb0+u\x01\xf1!4\x8f^\xf7\xeapK\xcbi\x95\xc3\xfb\xaa\xaf\x86\xe5\xf3\x0c\x80\xb8\xf4Ek\x89W\x94c\xaf\x85m\x01\xbc\xbeA$4\x1c\xb6\t\xa7Z\x9b\x10\xa2\xd1\x7f\xbe\xd9r\xf7\x90\xd2cpb\xba\xd6\xfaWb\xf2N\xe8\xf6\x07\x14\x15\x00[\x12\xdf(\xc31\x07p\x10\xb3\xf9\x1f\xe7\xe0`s{V\xfb*\xb9*\xcb\xf1\x0f\xf1\x00\x8c!]\t8\xf9\x16\xf8O\x06$_\x18C\x83\xab\xc8\xc7\xce=\xff\xab\x13\xb5e>D\xeaX@Rz\xdeZRR\x04\xa3!\x90I\x00jx2\xecp\xe0@p\x8fH5\xaaP\x8f\xa3\xdd\x04\xbf\x12@\x05\x15O\xe3\xa0\xe4\xfc?\'\xeb\xcb\xc9\x1c\xdbT\xccL\xcc<Xo\xc82\xf1\x990\xcd\x00\x97-{Fa?E\xa4\xad\x11*o?\xccN(\xea\xa7\xf5\x1c\xb4\x1a\x8f\xf6\x1d\x8d\xa8\xcbR\x98\xe4\xa7\x8f\xff\xff1,V3\x0b\x9b\xbd\xa4\xb1\xcb\x06;\xef\x12\xee\xbci\x11\xb0\x19\xabw\x00\xa9\xce\xbdQn\xee\x04\xdbW\xab\xf7\xe5{\xd3\xd3\x02\x08\x9d\xd7{V\xbb\x8a\xd2\xbc\xedJ\x82\xdb\xfb\xa4\x9a\xdb\x8a\x08\x02\xb5\xba\xa3\x14\xd1Y/\xe3% \xce\xdd\xfc\xae\\y\xc8\x95\x0c#$\xb8\x9eDA\xf8F%\x8br\xd1\x91o0\x12\xee\xc5\xc2\x05\x1c\\\xbe\xa5I\xc0\xbb\xa3,\nA\x13\x85\xba4(\x02\xcfb\xcc\xe3\xa2\xef\xc5\x87X\xcf\xd2\xb4F%y\xf6\x8a\x0eC|T\xbd\x82\xd9\x1e\x03\xd9\x1a\x1c\xb3\x12\xcb=\x87\xb8\x84\xb5xF\xba\xfc\xe8\xaf{t\xe1\x0f\xa8\x1dW\t\x1b\xd8N\xa3\xa1\x8d3\xcf{0!"aG\x1a\x06\x8f\xde\n\x18\x0c"H8\xef\xdew\xde\xdf\'\x0e\x85o\xd8\x00\xb1\x1e:\xa0\x1e\xe4\xbd\t)\x86\x9c1\x7f\x1f5\xc6s\x94\xe3\xfeY\x83\x174dw\xf7"(\xf4\xcb\xa1\xd4\r\xa2\xfc\xea\xc8\x9b\xdf\x95\xd6\x84;\xbcg^G\x1e\x0c\x93|:\x9b\x82:\x17\xf3\xca\xd3\xd6\xd0r\x1f\xc6\x1a\xc3\xab7\x80\x16<\\\xcd\x94\xbfxV\xd6f\xb0\xbb\xeb\r!\xae\xd5\x92hH\x1f=\x1bf<\x1c\x07\n\x8fFYW\xbd\xc7\x83\x8f,$\x9f\xc2m\x19\xb0%KM\xdb\xe6^\x14|\x82\xbe\x86\xaet\nw\xaa\xe2\xc3\x84\xb4\xccQ{\xa9Lp\x1d\x93+\x92\xb0L\xcc\x99\x08\x0b\xd2\xc4e\xb3\xc1\xb1\x9fK\x06\xde\xaeG\x18\xf2\x9c/ut.\x96\xf5\x94\x0e\xfb\xe8\xb7;\xc3\x08O\x7fag\xe1\xcd\x025\xff@\xf1\xe7\xf4\x075z\xc1\xb6\x9d$+\x13v\xa2\x06e\xa3\xc9\xa4\xb6\xbd?\xab\xa8\x9d\x99\xc7+\xb3MT#\xfbm\xee\xdf\x85\\\xf4D\xcb\xaf\xc7\x13\xaa\xdd\xf4\x96\x86!H\xa2\\c\xd2;\xd0\x8c\xb1\t\xf6\xfd\x03\xf2\xad\xd6\x1d\xea?\xde\xa9\xf40\x8c\xcd\xf6]_\tJ\xfc1V\xba*\xc20\xa4K\xba@x7"\x01\xacU\xd9\xf2n\x19c\xce.\x91H\xccx\xc1\x0cY\x01\x10\xe0\xf4?\x83[\xc0\x1d\x8a\x9eA\xfch\xcd\x8c2\xd6\xfc\xa8\x83\xacJ\x932\xb7\x98\x95\x8995\x19i\x9c\xd4\xceRs\xaa\x01\xccn\xc4$;\xc2\x8cp\xd3/3\xcd\xceO8\x07\xce\xa7\xd91w\x13\xc4\xb4\xe2HE\x92%\x04a\xf3\x88\xa0\x15\xe5\xe8\xb2\xbc\xd8\xad`\x92\xcd\xa6C\x9b\xcd\xd0\xff\xbd\xae\t\x1b\xe0\xdfW\xf9\xed\xe8\xd0\xc6Z\xb3\x878\x98\x1a\xd1\xb1\x95\xca\xc0&~\x15/\xa1\x89F\x9a\x01\xd7G,\x9a^\xa0\xca\xfb\xa6\xe9Q(&<\x00\x1d&\x8b\xd9\x97g\xdfd/\x92Y\x97k<\xf9^\xf1\x92\x96\xd6\xa1XG\x00\xa6\x04\x93\x94\xa0wA\xbe\x98\x83\xd28J\xf8\n\xb9\x84?\xaa\x07\x1d\t\xa0\xb5w4\xf8b\xe5y\x02`\xa2\x9a\xedR\xa97p\xea4\x07q6\x81p\x95\xbf\x0b\xc9\x92\xc7D\xaaL\xb2\xd0\xd6\x0bX\xb6\xb1\x1fm\x15(\xafSn\x93\x9c\xac\xb1Q\x00\xf2a[\xf7\x984\x94{VjB\xdf\xab\xd2a\xa4\xf0c\x9dV\x01#\x92!\x16Y-EFa\xbd\xc3\xfc*\xd0\x91\xce\x82\x916\x9el\x82\x90\x04\xaf\xbb\xeet\xba\r\xfa\x1c:\x05\x1f\xe4v\x17-s\x04$\xfbl\x142\x16\t6n\xed\x18\x0e\x9a\xc7\x1a\xa5\xccws\x89x\xa6\xd9<Y\xf2\xf2\xa3t\x8f\xe9Cj\x81\x90o\xa4O\xfe*\xed\r\x84\x86\xf2\xe8 \x9b\x00#\xf40\xb5[\x968)-\xf6\xcfokc\xa2H\xe6E\xf46\x19\x1e\x13\x95D\x11\x1f=N\xa6\x05R2B\x93\xdb\xb9\xcc\x12W\x05\xfb\x07\x80\x91\xdc\x99T#\x8f-M\xb1)\x19\xa9\x1561\xae3\xc4\xfbG\x96]\xf0HV\x0b\x80\xaa\x98g\x14~{\x1c\x1f\'L_\x02]M\xc8\xa3\xb7\xe07SF\x8a\xefs\xc3RQ[\x8c\x1aX \\\x86\xfb#\x0e\xa3\xb9H\xe1i`\xe6\x0e\x11\x948\xd4\x1aq\xf6\x9c\x97;\xd3a\xb1\xb9q\xb7\xb8\x80\xf2tV\xe7.\x89\x17\xdaPe\x05\x8f]\xd5o\x16Z\x8bl\xff\xb2\'?Oj\x06\xe5\xd61\xe5\xf3QZ\xcd\xea+\xaaJ\xd1\x9dj\xdf\xecN\x8fB\x02T\xc3W\xcct\xa47x<\x1e\xd3\x1b\x01p\xf1a\xf7\xad\xb8\x93\x80PY#b\xc3\xbe\xe0\xde\xd4q\xf1\xf7\x1aK\n\xc5V\xbd6A\x17\t&\xd7}`\x8e\xa0\xab6j2{V\xc2\x0f\x05\xef:\x9a\xe2)\x84\x8aP\xf1}\x01\x05\x7f\x1f*a&\xcf\x99J\xd6\x8eb\x91:l\xbb\x87o\xa6\xd8kr\xecl4\xb9\xb0\x92E$\x03_Jw\xde\xdb\x9a\x19\xe8\xf1c\xfb#\x1emCR\x94\xac\xf5\xad`\x1cB:\xe56\xbfQk\xb0\xb1\x0c\xe7\x17\x1c\x81\x80\xca\xa2\xd4\xc00\x8bE\x18\xe86\x90\xd0w+\x1e\xf76\xba\x8c\x8c\xd8\xf9\xcdO\xfe|\xc3\\\xe2\xec\xc7Xj\xaac\xa0wBP\xd8\xb5\xa2U\xbe\xa9^qO\xbas\xe4\xa3\x9e,\xdf\xcf\xd5\xfc:\x95\xc0[-\xeaf65>c\x06\xc3D\xa9\xad\x979m\xbb&.|\x0b\xdc\xaf\xf7\x8a=\x97+\x85\x7fzLRi{\x01\x11\x16\xcb>\x94\xcd\xa5\xefJ\x1d\xf7{\x13|\x95\xd4\x19Z\xc7\x00?z\xc6\x82U\x1e\xa5\x9bL\x05\x04@\x1b\xf9=\xb9\xe8\x90\xe17\n\x1a\xf3\xc7\xc6\x03\xc2o\xf47\x11\x86\x87\xf2\x14{=\xc6v`qZ0g\xa0\x0f\xd4\x98\x186}\x87\xf3%\x80\x05\x0eG];\xc2<&\x85\xfd\nL-U}z\x02\x12\xf4\x03\x96T\xb5\x12\xde\x18\x1c\x17\x857\x04\xd4\x8f\xe7\xfbA\xedY3\xcb\xa60w\xb8K7\x91X\xf1\x002u\xe4\xcb\x8a\xbe?\x83\x17\x81\x9a\xff\xf5\xd7\x94\xcb\xf6 EC\x17{\xe4\x04\x98\xe0i\x050\xdaD\xce\xeely\xbf\x14.\x0eG\x9e\xd6V\xf0i\r,\x05tmaA\x90b\xf9\xcc\xc1\xbd\x9an,\xf3\x07)\xc4\x18\x1c\xfbH\x04\xa5\x03\x1bt\x12\xfff\x1c\xc3/\x1f?\x9d\xbe\xf3\xaf\xeb.\'\xcevl\xb3&\xaf\x11\x8f\xc3W!z~\x90s\xce|\x11f\xeap\t\x8c\x07n\xc4)\x10\xc5L)\xafI\x92\xdbP/\xf7\xa2\xd4X\xf6\xf4\xd0\xd4\x8c\x93o\xde\xf8\x019\x91\ry*\xa2\x02#\xed\xcc\x86\r\xc4$\n\x03\xbd\x1dm\xf1\'\xb3\xdb\x87\\^o\xb5\xcd\xb7\xb3\xab\xae)V\n\xf6G\xb9< \xacY;\xb8\xfb^\xdcv,\x8e\x863\xde\xb7\xa8\xb9\x86\x96\x7f\xa3\xecB<\xd5\x80\x90\xe9\x06\x1cA\x9a\xdb\x11\xebU\x11\x00\xe9\xa8\xb13\xdf0%\xa7D\xa8\x9dp\xfc}\x92\x93O\x05I\xfe\x85\t\xf6;J\xb2\\\x85\x84\x93\xce\xbea\xdb\x88se\xcb\xdb\x85*\xe7\x872\x84G\xd5\xabo\xea\xf3\x15v\xb9\x7f\x1f.W"\x9d\x1bm\xb2\x8a\xff\x9c\x10Wn\n\xf9\xc1AMAj\xea\xbaFL\xba6"h\x82\xf4$OP\xe9<\x87\xa2\x0fJ\xef\xf2%\xe7\x04\' \xb1\xd4\x03A\xaeT\x05\xad\x8cJJ\x9f\x87\xba\xc1\xc7j\xafU\x87$-/Q\x86\xafeB]>r\xa4\xbc\xf5\xc0\x0841\xbe\x949\xe4E\x9e\xe8\xec\x97%\x15\x0eT\x8fh\xfd\x17jtB+KdR\xc5\xe6\xb1\x1e\xbcE\xac\xc5\xe8$v\xa2\x8a\x99\x80\xca\x1a\xc9\\\xb4\x19\x809~\xe1\x8c\xdd\xf8\xaaC\x1d\xadr\x82M\xdd\x9a\xeb\x11\x06\xae\xaab!\xe8\xda\x9e\xb9\xc6n\x0e\xcc\x84I\xa2\xd6/\x05\x13\xb6gU\xb6\x18\xc2+\xe44\x03\' \xd2\x8a>\xeb\x08aq;\x9b\x06\xaf\x0f\x01Z\x81\x1b\x00?\xbd\xd2\x7f"gi\xf7\xd2_\xf6\xb9\xe7\x07\xdaR\xee\xb0vC\x9c\xef~\xc7\x88\x91P\xf8;\x84\xd2/nC\x02+\xf7\x8c\x9c\xa0\xf0s\x8f\xea\xb0/\xd8t\xfeOE\xc0Z?\xcc\xb7\x8b\xf9\x98\x06\x93\xfc\xd7j.g\x8b\xeeg\xdf\x9aO'
	                data = 'G6koGovW3pnmvrBOu/GZ/JsplD6Kku04rjxUrqPR9UpVV2l45gJ+ZRQBySCkCXchyn2hyT+wK3UB8SE0j1736nBLy2mVw/uqr4bl8wyAuPRFa4lXlGOvhW0BvL5BJDQctgmnWpsQotF/vtly95DSY3Biutb6V2LyTuj2BxQVAFsS3yjDMQdwELP5H+fgYHN7VvsquSrL8Q/xAIwhXQk4+Rb4TwYkXxhDg6vIx849/6sTtWU+ROpYQFJ63lpSUgSjIZBJAGp4Muxw4EBwj0g1qlCPo90EvxJABRVP46Dk/D8n68vJHNtUzEzMPFhvyDLxmTDNAJcte0ZhP0WkrREqbz/MTijqp/UctBqP9h2NqMtSmOSnj///MSxWMwubvaSxywY77xLuvGkRsBmrdwCpzr1Rbu4E21er9+V709MCCJ3Xe1a7itK87UqC2/ukmtuKCAK1uqMU0Vkv4yUgzt38rlx5yJUMIyS4nkRB+EYli3LRkW8wEu7FwgUcXL6lScC7oywKQROFujQoAs9izOOi78WHWM/StEYlefaKDkN8VL2C2R4D2RocsxLLPYe4hLV4Rrr86K97dOEPqB1XCRvYTqOhjTPPezAhImFHGgaP3goYDCJIOO/ed97fJw6Fb9gAsR46oB7kvQkphpwxfx81xnOU4/5Zgxc0ZHf3Iij0y6HUDaL86sib35XWhDu8Z15HHgyTfDqbgjoX88rT1tByH8Yaw6s3gBY8XM2Uv3hW1mawu+sNIa7VkmhIHz0bZjwcBwqPRllXvceDjywkn8JtGbAlS03b5l4UfIK+hq50Cneq4sOEtMxRe6lMcB2TK5KwTMyZCAvSxGWzwbGfSwberkcY8pwvdXQulvWUDvvotzvDCE9/YWfhzQI1/0Dx5/QHNXrBtp0kKxN2ogZlo8mktr0/q6idmccrs01UI/tt7t+FXPREy6/HE6rd9JaGIUiiXGPSO9CMsQn2/QPyrdYd6j/eqfQwjM32XV8JSvwxVroqwjCkS7pAeDciAaxV2fJuGWPOLpFIzHjBDFkBEOD0P4NbwB2KnkH8aM2MMtb8qIOsSpMyt5iViTk1GWmc1M5Sc6oBzG7EJDvCjHDTLzPNzk84B86n2TF3E8S04khFkiUEYfOIoBXl6LK82K1gks2mQ5vN0P+9rgkb4N9X+e3o0MZas4c4mBrRsZXKwCZ+FS+hiUaaAddHLJpeoMr7pulRKCY8AB0mi9mXZ99kL5JZl2s8+V7xkpbWoVhHAKYEk5Sgd0G+mIPSOEr4CrmEP6oHHQmgtXc0+GLleQJgoprtUqk3cOo0B3E2gXCVvwvJksdEqkyy0NYLWLaxH20VKK9TbpOcrLFRAPJhW/eYNJR7VmpC36vSYaTwY51WASOSIRZZLUVGYb3D/CrQkc6CkTaebIKQBK+77nS6DfocOgUf5HYXLXMEJPtsFDIWCTZu7RgOmscapcx3c4l4ptk8WfLyo3SP6UNqgZBvpE/+Ku0NhIby6CCbACP0MLVbljgpLfbPb2tjokjmRfQ2GR4TlUQRHz1OpgVSMkKT27nMElcF+weAkdyZVCOPLU2xKRmpFTYxrjPE+0eWXfBIVguAqphnFH57HB8nTF8CXU3Io7fgN1NGiu9zw1JRW4waWCBchvsjDqO5SOFpYOYOEZQ41Bpx9pyXO9Nhsblxt7iA8nRW5y6JF9pQZQWPXdVvFlqLbP+yJz9Pagbl1jHl81FazeorqkrRnWrf7E6PQgJUw1fMdKQ3eDwe0xsBcPFh9624k4BQWSNiw77g3tRx8fcaSwrFVr02QRcJJtd9YI6gqzZqMntWwg8F7zqa4imEilDxfQEFfx8qYSbPmUrWjmKROmy7h2+m2Gty7Gw0ubCSRSQDX0p33tuaGejxY/sjHm1DUpSs9a1gHEI65Ta/UWuwsQznFxyBgMqi1MAwi0UY6DaQ0HcrHvc2uoyM2PnNT/58w1zi7MdYaqpjoHdCUNi1olW+qV5xT7pz5KOeLN/P1fw6lcBbLepmNjU+YwbDRKmtlzltuyYufAvcr/eKPZcrhX96TFJpewERFss+lM2l70od93sTfJXUGVrHAD96xoJVHqWbTAUEQBv5PbnokOE3Chrzx8YDwm/0NxGGh/IUez3GdmBxWjBnoA/UmBg2fYfzJYAFDkddO8I8JoX9CkwtVX16AhL0A5ZUtRLeGBwXhTcE1I/n+0HtWTPLpjB3uEs3kVjxADJ15MuKvj+DF4Ga//XXlMv2IEVDF3vkBJjgaQUw2kTO7mx5vxQuDkee1lbwaQ0sBXRtYUGQYvnMwb2abizzBynEGBz7SASlAxt0Ev9mHMMvHz+dvvOv6y4nznZssyavEY/DVyF6fpBzznwRZupwCYwHbsQpEMVMKa9JkttQL/ei1Fj29NDUjJNv3vgBOZENeSqiAiPtzIYNxCQKA70dbfEns9uHXF5vtc23s6uuKVYK9ke5PCCsWTu4+17cdiyOhjPet6i5hpZ/o+xCPNWAkOkGHEGa2xHrVREA6aixM98wJadEqJ1w/H2Sk08FSf6FCfY7SrJchYSTzr5h24hzZcvbhSrnhzKER9Wrb+rzFXa5fx8uVyKdG22yiv+cEFduCvnBQU1Bauq6Rky6NiJogvQkT1DpPIeiD0rv8iXnBCcgsdQDQa5UBa2MSkqfh7rBx2qvVYckLS9Rhq9lQl0+cqS89cAINDG+lDnkRZ7o7JclFQ5Uj2j9F2p0QitLZFLF5rEevEWsxegkdqKKmYDKGslctBmAOX7hjN34qkMdrXKCTd2a6xEGrqpiIejanrnGbg7MhEmi1i8FE7ZnVbYYwivkNAMnINKKPusIYXE7mwavDwFagRsAP73SfyJnaffSX/a55wfaUu6wdkOc737HiJFQ+DuE0i9uQwIr94ycoPBzj+qwL9h0/k9FwFo/zLeL+ZgGk/zXai5ni+5n35pPSXowQWtkdFVITHVYbGk5UmR3bVlXb2tOM05ON2ptcXVvWTNMUWFnUGFlRk11L3JTYjBtU2NudXpPWFQ4d2Y4eA=='

Frame load in /share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/internal/Plugin.py at line 337
	              decode = True
	             cookies = True
	                 val = False
	                 get = {}
	                 url = u'http://service.jdownloader.org/dlcrypt/service.php?srcType=dlc&destType=pylo&data=SXowQWtkdFVITHVYbGk5UmR3bVlXb2tOM05ON2ptcXVvWTNMUWFnUGFlRk11L3JTYjBtU2NudXpPWFQ4d2Y4eA=='
	                self = <userplugins.container.DLC.DLC object at 0x870594c>
	                 req = <module.network.Browser.Browser object at 0xf3c450ec>
	           multipart = False
	                 key = 'just_header'
	                post = {}
	                 ref = True
	         just_header = False

PLUGIN OBJECT DUMP: 

	             API_URL = 'http://service.jdownloader.org/dlcrypt/service.php?srcType=dlc&destType=pylo&data=%s'
	                  IV = '9bc24cb995cb8db3'
	                 KEY = 'cb99b5cbc24db398'
	             account = None
	             captcha = <module.plugins.internal.Captcha.Captcha object at 0xf3c72aac>
	         chunk_limit = 1
	                html = None
	                info = {}
	                  js = <module.common.JsEngine.JsEngine instance at 0x842fa2c>
	          last_check = None
	       last_download = ''
	             limitDL = 0
	             multiDL = True
	            packages = []
	             premium = False
	              pyfile = PyFile 1: tmp_n2wdn156jeese93.dlc@DLC
	              pyload = <__main__.Core object at 0x822d88c>
	                 req = <module.network.Browser.Browser object at 0xf3c450ec>
	     resume_download = False
	             retries = {}
	          retry_free = False
	              thread = <DecrypterThread(Thread-12, started daemon)>
	                urls = []
	                user = None
	          wait_until = 0
	             waiting = False
	       wantReconnect = False

PYFILE OBJECT DUMP: 

	               _size = 0
	               abort = False
	              active = False
	               error = "'DLC' object has no attribute 'COOKIES'"
	                  id = 1
	                lock = <_RLock(None, 0)>
	                   m = <module.database.FileDatabase.FileHandler instance at 0x823c1cc>
	         maxprogress = 100
	                name = u'tmp_n2wdn156jeese93.dlc'
	               order = 0
	           packageid = 1
	              plugin = <userplugins.container.DLC.DLC object at 0x870594c>
	         pluginclass = <class 'userplugins.container.DLC.DLC'>
	        pluginmodule = <module 'userplugins.container.DLC' from '/share/CACHEDEV1_DATA/.qpkg/pyload/data/userplugins/container/DLC.pyc'>
	          pluginname = u'DLC'
	            progress = 0
	         reconnected = False
	                size = 0
	              status = 8
	          statusname = None
	                 url = u'Downloads/tmp_n2wdn156jeese93.dlc'
	           waitUntil = 0

URL:

HOSTER UploadedTo[4]: PROCESS URL http://ul.to/file/o41isx | PLUGIN VERSION 0.96
 INFO      HOSTER UploadedTo[4]: Updating file info...
 DEBUG     HOSTER UploadedTo[4]: File info: {'status': 1, 'url': u'http://uploaded.net/file/o41isx', 'size': 0, 'name': u'o41isx', 'pattern': {'ID': u'o41isx'}}
 DEBUG     HOSTER UploadedTo[4]: Previous file info: {}
 INFO      HOSTER UploadedTo[4]: File name: o41isx
 INFO      HOSTER UploadedTo[4]: File size: Unknown
INFO      HOSTER UploadedTo[4]: File status: offline
 DEBUG     HOSTER UploadedTo[4]: Config option `fallback` not found, use default `True`
WARNING   Download failed: o41isx | offline
INFO      HOOK UnSkipOnFail: Looking for skipped duplicates of: o41isx (pid:4)
INFO      HOOK UnSkipOnFail: No duplicates found
DEBUG     HOOK AndroidPhoneNotify: LOAD URL http://www.notifymyandroid.com/publicapi/notify | decode=True | cookies=True | get={'application': 'pyLoad', 'apikey': u'1f00f66d4fbbe01a7f9bd7ac53798cf15697ee009ad5c07a', 'event': u'Package failed', 'description': u'One or more packages was not completed successfully'} | req=None | _[1]=['decode=True', 'cookies=True', "get={'application': 'pyLoad', 'apikey': u'1f00f66d4fbbe01a7f9bd7ac53798cf15697ee009ad5c07a', 'event': u'Package failed', 'description': u'One or more packages was not completed successfully'}", 'req=None'] | multipart=False | post={} | ref=True | just_header=False
WARNING   Error calling event handler allDownloadsProcessed: <bound method AndroidPhoneNotify.all_downloads_processed of <Addon AndroidPhoneNotify>>, (), 'AndroidPhoneNotify' object has no attribute 'COOKIES'
DEBUG     All downloads processed

After Update from 02.08.2015 evening not more worked.

**Comment by sraedler** [comment]
dlc is working

please close
